### ISSUE TITLE
NetMQ doesn't appear to communicate with pyzmq?

### ISSUE THREAD

**Issue by ruamegatrader** [NetMQ/Samples#16]
When I use ZeroMQ library or ZMQ library (from NUGET), I can communicate perfectly fine between C# and Python (pyzmq).
However, when I use NetMQ, I cannot get any interoperability between them.

I've attempted PUB/SUB and REP/REQ - as mentioned - they work well with the other two C# libraries and Python (both as initiator and receiver and vice-versa), but Python doesn't see anything whatsoever when using NetMQ. From the print statements in my code, it looks like NetMQ claims it has sent messages, but nothing is seen by Python and vice-versa in the other direction.

It's the same code for all three libraries (as ZeroMQ/ZMQ). I really don't know what is going on. Using Python 3.8.7 and examples from github from all three C# libraries.

Could you kindly investigate this? With thanks!

**Comment by dyurk1113** [comment]
Did you ever find a resolution to this? I'm running into the same issue.

**Comment by ruamegatrader** [comment]
Sorry, but no, I did not. With the other libraries not providing the functionality I needed, and NetMQ not working, I decided to drop C# and go full Python, and it worked well from that point onwards.
